AltCloud\Instance3Bundle\Entity\Node:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    machine_name:
      type: string
      length: '255'
    mode:
      type: string
      length: '12'
    target_entity:
      type: string
      length: '255'
    target_view:
      type: string
      length: '255'
    target_params:
      type: array
    label:
      type: string
      length: '120'
      nullable: true
    title:
      type: string
      length: '120'
  lifecycleCallbacks: {  }
  oneToMany:
    children:
      targetEntity: Node
      mappedBy: parent
  manyToOne:
    parent:
      targetEntity: Node
      inversedBy: children
    site:
      targetEntity: Site
      inversedBy: nodes
      joinColumn:
        name: site_id
        referencedColumnName: id