AltCloud\Instance3Bundle\Entity\Site:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: '255'
    url:
      type: string
      length: '120'
    deftemp:
      type: string
      length: '80'
  lifecycleCallbacks: {  }
  oneToMany:
    nodes:
      targetEntity: Node
      mappedBy: site
  oneToOne:
    entrynode:
      targetEntity: Node