ac_inst3:
    contentmodels:
        ACInst3MediaBundle:
            Media:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
                listmodes:
                    list:
                        rendermode: forward
                        view: list.html.twig
                    listPartial:
                        rendermode: display
                        view: listPartial.html.twig
                    matrixPartial:
                        rendermode: display
                        view: matrixPartial.html.twig
                    accordionPartial:
                        rendermode: display
                        view: accordionPartial.html.twig
            Gallery:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
            Format:
                displaymodes:
                    renderPartial:
                        rendermode: display
                        view: display.html.twig
        ACInst3BlogBundle:
            Post:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
                listmodes:
                    list:
                        rendermode: forward
                        view: list.html.twig
                    listPartial:
                        rendermode: display
                        view: listPartial.html.twig
            Category:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
        ACInst3EventBundle:
            Event:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
                listmodes:
                    list:
                        rendermode: forward
                        view: list.html.twig
                    listPartial:
                        rendermode: display
                        view: listPartial.html.twig
            Agenda:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
        ACInst3LocationBundle:
            Location:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
                    plotPartial:
                        rendermode: display
                        view: plotPartial.html.twig
                listmodes:
                    list:
                        rendermode: forward
                        view: list.html.twig
                    listPartial:
                        rendermode: display
                        view: listPartial.html.twig
                    plotPartial:
                        rendermode: display
                        view: plotPartial.html.twig
        ACInst3GridBundle:
            Grid:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig