ACInst3Bundle_node:
    pattern:  /fw/{id}
    defaults: { _controller: ACInst3Bundle:Node:forward }

node_show:
    pattern:  /show/{mname}/{params}
    defaults: { _controller: ACInst3Bundle:Node:forward, params: false }
    requirements:
        params: ".+"

ACInst3Bundle_site_entry:
    pattern:  /
    defaults: { _controller: ACInst3Bundle:Site:entry }

ACInst3Bundle_spec_site_entry:
    pattern:  /site/{url}
    defaults: { _controller: ACInst3Bundle:Site:entry }

ACInst3Bundle_text:
    pattern:  /text/{id}
    defaults: { _controller: ACInst3Bundle:Text:render }