ACInst3Bundle_admin_node:
    resource: "@ACInst3Bundle/Resources/config/routing/node.yml"
    prefix:   /admin/node
    
ACInst3Bundle_node:
    pattern:  /fw/{id}
    defaults: { _controller: ACInst3Bundle:Node:forward }

node_show:
    pattern:  /show/{mname}/{params}
    defaults: { _controller: ACInst3Bundle:Node:forward, params: false }
    requirements:
        params: ".+"

ACInst3Bundle_admin_site:
    resource: "@ACInst3Bundle/Resources/config/routing/site.yml"
    prefix:   /admin/site
    
ACInst3Bundle_site_entry:
    pattern:  /
    defaults: { _controller: ACInst3Bundle:Site:entry }

ACInst3Bundle_spec_site_entry:
    pattern:  /site/{url}
    defaults: { _controller: ACInst3Bundle:Site:entry }

ACInst3Bundle_admin_text:
    resource: "@ACInst3Bundle/Resources/config/routing/text.yml"
    prefix:   /admin/text
    
ACInst3Bundle_text:
    pattern:  /text/{id}
    defaults: { _controller: ACInst3Bundle:Text:render }