parameters:
#    ac_inst3.example.class: AltCloud\Instance3Bundle\Example
     ac_inst3.contentmodels:
        ACInst3MediaBundle:
            Media:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
                listmodes:
                    list:
                        rendermode: forward
                        view: list.html.twig
                    listPartial:
                        rendermode: display
                        view: listPartial.html.twig
                    matrixPartial:
                        rendermode: display
                        view: matrixPartial.html.twig
                    accordionPartial:
                        rendermode: display
                        view: accordionPartial.html.twig
            Gallery:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
            Format:
                displaymodes:
                    renderPartial:
                        rendermode: display
                        view: display.html.twig
        ACInst3BlogBundle:
            Post:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
                listmodes:
                    list:
                        rendermode: forward
                        view: list.html.twig
                    listPartial:
                        rendermode: display
                        view: listPartial.html.twig
            Category:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
        ACInst3EventBundle:
            Event:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
                listmodes:
                    list:
                        rendermode: forward
                        view: list.html.twig
                    listPartial:
                        rendermode: display
                        view: listPartial.html.twig
            Agenda:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
        ACInst3LocationBundle:
            Location:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig
                    plotPartial:
                        rendermode: display
                        view: plotPartial.html.twig
                listmodes:
                    list:
                        rendermode: forward
                        view: list.html.twig
                    listPartial:
                        rendermode: display
                        view: listPartial.html.twig
                    plotPartial:
                        rendermode: display
                        view: plotPartial.html.twig
        ACInst3GridBundle:
            Grid:
                displaymodes:
                    render:
                        rendermode: forward
                        view: render.html.twig
                    renderPartial:
                        rendermode: display
                        view: renderPartial.html.twig

services:
#    ac_inst3.example:
#        class: %ac_inst3.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#
#    ac_inst3.menu_builder:
#        class: AltCloud\Instance3Bundle\Menu\MenuBuilder
#        arguments: ["@knp_menu.factory"]
#
#    ac_inst3.menu.main:
#        class: Knp\Menu\MenuItem # the service definition requires setting the class
#        factory_service: ac_inst3.menu_builder
#        factory_method: createMainMenu
#        arguments: ["@request"]
#        scope: request # needed as we have the request as a dependency here
#        tags:
#            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
#
    ac_inst3.cmscontentmodels:
        class: AltCloud\Instance3Bundle\CMS\ContentModels
        arguments: [%ac_inst3.contentmodels%]

    ac_inst3.twig.instance_extension:
        class: AltCloud\Instance3Bundle\Twig\InstanceExtension
        tags:
            - { name: twig.extension }