admin_site:
    pattern:  /
    defaults: { _controller: "ACInst3Bundle:Site:index" }

admin_site_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACInst3Bundle:Site:show" }

admin_site_new:
    pattern:  /new
    defaults: { _controller: "ACInst3Bundle:Site:new" }

admin_site_create:
    pattern:  /create
    defaults: { _controller: "ACInst3Bundle:Site:create" }
    requirements: { _method: post }

admin_site_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACInst3Bundle:Site:edit" }

admin_site_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACInst3Bundle:Site:update" }
    requirements: { _method: post }

admin_site_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACInst3Bundle:Site:delete" }
    requirements: { _method: post }
