admin_text:
    pattern:  /
    defaults: { _controller: "ACInst3Bundle:Text:index" }

admin_text_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACInst3Bundle:Text:show" }

admin_text_new:
    pattern:  /new
    defaults: { _controller: "ACInst3Bundle:Text:new" }

admin_text_create:
    pattern:  /create
    defaults: { _controller: "ACInst3Bundle:Text:create" }
    requirements: { _method: post }

admin_text_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACInst3Bundle:Text:edit" }

admin_text_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACInst3Bundle:Text:update" }
    requirements: { _method: post }

admin_text_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACInst3Bundle:Text:delete" }
    requirements: { _method: post }
